# MONGODB
#用于签名的MongoDB数据库
#spring.data.mongodb.authentication-database=
#数据库名称
#spring.data.mongodb.database=test
#使用字段策略
#spring.data.mongodb.field-naming-strategy=
#GridFS（网格文件）数据库名称
#spring.data.mongodb.grid-fs-database=
#MongoDB服务器，不能设置为URI
#spring.data.mongodb.host=47.100.238.158
#MongoDB服务器用户密码
#spring.data.mongodb.password=123456
#MongoDB服务器端口
#spring.data.mongodb.port=27017
#是否启用MongoDB关于jpa的编程
#spring.data.mongodb.repositories.type=auto
#MongoDB默认URI
#spring.data.mongodb.uri=
#spring.data.mongodb.username=root

#spring.data.mongodb.uri= mongodb://47.100.238.158:27017/test